version: '3'

services:
  influxdb:
    image: influxdb:1.11
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_BUCKET}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
    links:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  monitoring:
    driver: bridge 

